version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres_greenlight
    # restart policy to make sure the container is restarted automatically when your machine is rebooted
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volume/postgress:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: adminUsr
      POSTGRES_PASSWORD: adminadmin
